### ISSUE TITLE
How to handle out of memory error?

### ISSUE THREAD

**Issue by dhariyalbhaskar** [kmpoon/hlta#10]
I am trying to extract the topics from [CFPB](https://www.consumerfinance.gov/) dataset, but it is breaking in between due to OOM error. I have 16 GB of RAM which is enough for this dataset I hope.

![image](https://user-images.githubusercontent.com/20501023/50139913-14abdb80-02c9-11e9-9511-64632eda426c.png)

**Comment by kmpoon** [comment]
You may try using the -Xmx flag for Java runtime:

```java -Xmx14G -cp HLTA.jar:HLTA-deps.jar tm.text.Convert myData ./source 1000 1```
