### ISSUE TITLE
How to fit model to unseen document? 

### ISSUE THREAD

**Issue by Benja1972** [kmpoon/hlta#13]
In LDA methods after creation of topics model we can fit unseen document and get topics distribution on it. I wonder if it is possible with HLTA model? How to annotate  unseen document by topics already created by HLTA model? 

Thank you

**Comment by kmpoon** [comment]
You may use the [Doc2Vec Assignment](https://github.com/kmpoon/hlta#subroutine-4-doc2vec-assignment) to do so.  You will need to convert the unseen document to a binary vector as the input data.  Each element in the vector corresponds to a word (in the same order) in the vocabulary  you used to train the model.

**Comment by Benja1972** [comment]
Thank you! Very informative, I will try
