### ISSUE TITLE
Why Pdf format

### ISSUE THREAD

**Issue by saria85** [kmpoon/hlta#4]
as most of the dataset are .txt  may please explain why you required the files be .pdf in the extracted part?

I am going work on the newsgroup but I can not find .pdf format, I know that I can convert but its going to be waste of time, I was thinking maybe you have a reason for doing this,

**Comment by kmpoon** [comment]
The reason is we had to start with PDF files for building a topic browsing system for research papers:

https://link.springer.com/chapter/10.1007%2F978-3-319-63564-4_32
