### ISSUE TITLE
extract more topics

### ISSUE THREAD

**Issue by sariagoudarzvand** [kmpoon/hlta#8]
Hello again :)

I have applied your approach on very large medical dataset. It outputs 5 topics and each topic only have one sub - category.
1. What should be the parameters or to better say how can I increase the number of topics to at least 10?
the only thing is increasing the number of words extracted in the Convert step?

2. and why there is that much repetitive words among clusters of the topic? I mainly mean its not good to see a topic or a word both in the lower level and the same in the upper level.

Thanks:)

**Comment by kmpoon** [comment]
How many words (observed variables) do you have in your data set?  And can you send the topic / model you have, perhaps by email (kmpoon@eduhk.hk)?

**Comment by saria85** [comment]
Thanks for replying soon :)
I will send tomorrow, it has 5 topics, and then each topic has its own subcategories by three level overall.
I do not know the number of words in my dataset its almost 200mg data, 500K documents(number of documents is 500 000).

**Comment by kmpoon** [comment]
During [Subroutine 1](https://github.com/kmpoon/hlta#subroutine-1-convert-text-files-to-data), you need to specify the number of words (e.g. 1000 in the README).  How many words did you specify?

**Comment by saria85** [comment]
Sorry I thought I mentioned that, I first tried with 1000 it gave me 5 topics then I changed to 2000 and it only added one more and became 6 topic.

**Comment by saria85** [comment]
may I have your email, I can email model but sadly can not share data.
Its the latest version I updated the previous one.
BTW, input data is clinical notes related to patients, Im going to do some specific preprocessing then apply the approach and explore the result. I will update here the improvement.

Thanks.

**Comment by kmpoon** [comment]
My email is kmpoon@eduhk.hk.

If the problem persists, you may try to use an older version (e.g. v1.4.1) to see if it could give you a better model.

**Comment by saria85** [comment]
I decided to do more preprocessing then share my exprience here. seems when I make my data smaller it gives me more topics.

what are the numbers in each topic? I cant see a pattern on them. are they the probability?

**Comment by saria85** [comment]
one more question, why the extracted topics are a little bit messy. for example in one topic there are only two word distribution, in another one there are 10, it makes it hard to intrepret the result, what will be a topic with only two word?

appreciate your feedback:)

**Comment by kmpoon** [comment]
Those topics at bottom may have very few keywords.  The reason is that the latent variables corresponding to those topics can have only two descendent observed variables.

Since the keywords are ordered in importance, you may consider only the first few keywords of a topics.  You may also ignore the topics at the lowest one or two levels if you think they are too specific.
